app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
| Route Model Binding defined in RouteServiceProvider Class
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);


/**
 *
 * Categories Routes
**/
// Get the current user's category by type in json format, used in fixed transaction form
Route::get('api/categories/type/{type_id}', 'CategoriesController@getUserCategoriesByType');

// view inactive/trashed categories
Route::get('categories/inactive', ['as' => 'categories.indexInactive', 'uses' => 'CategoriesController@indexInactive']);

// deactivate/trash categories
Route::get('categories/{categories}/deactivate', ['as' => 'categories.deactivate', 'uses' => 'CategoriesController@softDelete']);

// activate trashed categories
Route::get('categories/{categories}/activate', ['as' => 'categories.activate', 'uses' => 'CategoriesController@softStore']);

// creates RESTFUL routes
Route::resource('categories', 'CategoriesController');


/**
 *
 * Fixed transactions Routes
 **/
// Create the monthly fixed transactions into transactions (for use with cron)
Route::get('fixed-transactions/sync-cron', 'FixedTransactionsController@generateMonthlyFixedTransactionsCron');

// Create the monthly fixed transactions into transactions 
Route::get('fixed-transactions/sync', ['as' => 'fixed-transactions.sync', 'uses' => 'FixedTransactionsController@generateMonthlyFixedTransactions']);

// view inactive/trashed fixed transactions
Route::get('fixed-transactions/inactive', ['as' => 'fixed-transactions.indexInactive', 'uses' => 'FixedTransactionsController@indexInactive']);

// deactivate/trash fixed transactions
Route::get('fixed-transactions/{fixed_transactions}/deactivate', ['as' => 'fixed-transactions.deactivate', 'uses' => 'FixedTransactionsController@softDelete']);

// activate trashed fixed transactions
Route::get('fixed-transactions/{fixed_transactions}/activate', ['as' => 'fixed-transactions.activate', 'uses' => 'FixedTransactionsController@softStore']);

// creates RESTFUL routes
Route::resource('fixed-transactions', 'FixedTransactionsController');


/**
 *
 * Transactions Routes
 **/
// creates RESTFUL routes
Route::resource('transactions', 'TransactionsController');


/**
 *
 * User Routes
 **/
// creates RESTFUL routes
Route::resource('users', 'UsersController');
Route::get('user/change-password', ['as' => 'users.changePassword', 'uses' => 'UsersController@changePassword']);

/**
 *
 * API Routes
**/
Route::get('api/categories', 'CategoriesController@getUserCategories');
Route::post('api/categories', 'CategoriesController@store2');

// Get the user's transactions in json format
Route::get('api/transactions', 'TransactionsController@getTransactions');

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Mis Cuentas Online</title>

    <meta name=viewport content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ elixir('css/all.css') }}" >

    <link rel="stylesheet" href="/css/angular-chart.css">

	@yield('header')

</head>
<body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Mis Cuentas Online</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          @if($user)
            <ul class="nav navbar-nav">
                <li>
                    <a href="{{ route('fixed-transactions.index') }}" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                        Transacciones Fijas
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('fixed-transactions.index') }}">Ver Transacciónes Fijas</a></li>
                        <li><a href="{{ route('fixed-transactions.indexInactive') }}">Ver Transacciónes Fijas Inactivas</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ route('fixed-transactions.create') }}">Crear Transacción Fija</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{{ route('categories.index') }}" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                        Categorias
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('categories.index') }}">Ver Categorias</a></li>
                        <li><a href="{{ route('categories.indexInactive') }}">Ver Categorias Inactivas</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ route('categories.create') }}">Crear Categoria</a></li>
                    </ul>
                </li>          
            </ul>
          @endif
          <ul class="nav navbar-nav navbar-right">
              <li class="active">
                  @if($user)
                      <a href="{{ route('users.index') }}" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                          {{ $user->name }}
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                          <li><a href="{{ route('users.index') }}">Perfil</a></li>
                          <li><a href="{{ route('users.index') }}">Opciones</a></li>
                          <li><a href="#">Sobre la aplicación</a></li>
                          <li role="separator" class="divider"></li>
                          <li><a href="/auth/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Salir</a></li>
                      </ul>
                  @else
                     <a href="/auth/login"><span class="glyphicon glyphicon-user" aria-hidden="true"></span><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Ingresar</a>
                  @endif
              </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  @yield('container', '<div class="container">')
    @if (Session::has('flash_message'))
        <div class="alert alert-{{ Session::get('flash_action') }}">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ Session::get('flash_message') }}
        </div>
    @endif

		@yield('content')

	</div>

	@yield('footer')

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

    <script type="text/javascript">
      $(function() {
        //enable nav dropdown menu on hover
        $('.nav li').hover(function(){
            $(this).addClass('open');
        }, function(){
            $(this).removeClass('open');
        });
      });

    </script>

    @yield('javascript')

</body>
</html>