app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
| Route Model Binding defined in RouteServiceProvider Class
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);


/**
 *
 * Categories Routes
**/
// Get the current user's category by type in json format, used in fixed transaction form
Route::get('api/categories/type/{type_id}', 'CategoriesController@getUserCategoriesByType');

// view inactive/trashed categories
Route::get('categories/inactive', ['as' => 'categories.indexInactive', 'uses' => 'CategoriesController@indexInactive']);

// deactivate/trash categories
Route::get('categories/{categories}/deactivate', ['as' => 'categories.deactivate', 'uses' => 'CategoriesController@softDelete']);

// activate trashed categories
Route::get('categories/{categories}/activate', ['as' => 'categories.activate', 'uses' => 'CategoriesController@softStore']);

// creates RESTFUL routes
Route::resource('categories', 'CategoriesController');


/**
 *
 * Fixed transactions Routes
 **/
// Create the monthly fixed transactions into transactions (for use with cron)
Route::get('fixed-transactions/sync-cron', 'FixedTransactionsController@generateMonthlyFixedTransactionsCron');

// Create the monthly fixed transactions into transactions 
Route::get('fixed-transactions/sync', ['as' => 'fixed-transactions.sync', 'uses' => 'FixedTransactionsController@generateMonthlyFixedTransactions']);

// view inactive/trashed fixed transactions
Route::get('fixed-transactions/inactive', ['as' => 'fixed-transactions.indexInactive', 'uses' => 'FixedTransactionsController@indexInactive']);

// deactivate/trash fixed transactions
Route::get('fixed-transactions/{fixed_transactions}/deactivate', ['as' => 'fixed-transactions.deactivate', 'uses' => 'FixedTransactionsController@softDelete']);

// activate trashed fixed transactions
Route::get('fixed-transactions/{fixed_transactions}/activate', ['as' => 'fixed-transactions.activate', 'uses' => 'FixedTransactionsController@softStore']);

// creates RESTFUL routes
Route::resource('fixed-transactions', 'FixedTransactionsController');


/**
 *
 * Transactions Routes
 **/
// creates RESTFUL routes
Route::resource('transactions', 'TransactionsController');


/**
 *
 * User Routes
 **/
// creates RESTFUL routes
Route::resource('users', 'UsersController');
Route::get('user/change-password', ['as' => 'users.changePassword', 'uses' => 'UsersController@changePassword']);

/**
 *
 * API Routes
**/
Route::get('api/categories', 'CategoriesController@getUserCategories');
Route::post('api/categories', 'CategoriesController@store2');

// Get the user's transactions in json format
Route::get('api/transactions', 'TransactionsController@getTransactions');

app/Http/Controllers/FixedTransactionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use App\Http\Requests;
use App\Http\Requests\FixedTransactionRequest;
use App\FixedTransaction;
use Illuminate\Support\Facades\Auth;
use App\Category;

class FixedTransactionsController extends Controller
{
	private $types;

	/**
	 * Loads Authentication middleware for all methods
	 *
	 * FixedTransactionController constructor.
	 */
	public function __construct()
	{
		$this->middleware('auth');

		$this->types = Collection::make(['Seleccione...', config('constants.TYPE.expense'), config('constants.TYPE.income')]);
	}

	/**
	 * View the active fixed transactions
	 *
	 * @return \Illuminate\View\View
     */
	public function index()
	{
		$fixed_transactions = Auth::user()->fixedTransactions;

		return view('fixed_transactions.index', compact('fixed_transactions'));
	}

	/**
	 * View the inactive fixed transactions
	 *
	 * @return \Illuminate\View\View
	 */
	public function indexInactive()
	{
		$fixed_transactions = Auth::user()->fixedTransactions()->onlyTrashed()->get();

		return view('fixed_transactions.index_inactive', compact('fixed_transactions'));
	}

	/**
	 * View a fixed transaction
	 *
	 * @param FixedTransaction $fixed_transaction
	 * @return \Illuminate\View\View
     */
	public function show(FixedTransaction $fixed_transaction)
	{
		return view('fixed_transactions.show', compact('fixed_transaction'));
	}

	/**
	 * View the create a fixed transaction page
	 *
	 * type: 1.fixed expense 2.fixed income 3.debt
	 *
	 * @return \Illuminate\View\View
	 */
	public function create()
	{
		$types = $this->types;

		return view('fixed_transactions.create', compact('types'));
	}

	/**
	 * View the edit a fixed transaction page
	 *
	 * @param FixedTransaction $fixed_transaction
	 * @return \Illuminate\View\View
	 */
	public function edit(FixedTransaction $fixed_transaction)
	{
		$types = $this->types;

		$categories = Category::getUserCategoriesByType(0);

		return view('fixed_transactions.edit', compact('fixed_transaction', 'types', 'categories'));
	}

	/**
	 * Creates a fixed transaction
	 *
	 * @param FixedTransactionRequest $request
	 * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
	 */
	public function store(FixedTransactionRequest $request)
	{
		$created = Auth::user()->fixedTransactions()->create($request->all());

		if ($created)
		{
			session()->flash('flash_message', 'La transacción fija ha sido creada.');
			session()->flash('flash_action', 'success');
		}
		else
		{
			session()->flash('flash_message', 'Hubo un error creando la transacción fija');
			session()->flash('flash_action', 'danger');
		}

		return redirect()->route('fixed-transactions.index');
	}

	/**
	 * Activates a fixed transaction
	 *
	 * @param FixedTransaction $fixed_transaction
	 * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
	 */
	public function softStore(FixedTransaction $fixed_transaction)
	{
		$activated = $fixed_transaction->restore();

		if ($activated)
		{
			session()->flash('flash_message', 'La transacción fija ha sido activada.');
			session()->flash('flash_action', 'success');
		}
		else
		{
			session()->flash('flash_message', 'Hubo un error activando la transacción fija');
			session()->flash('flash_action', 'danger');
		}

		return redirect()->route('fixed-transactions.indexInactive');
	}

	/**
	 * Updates a fixed transaction
	 *
	 * @param FixedTransaction $fixed_transaction
	 * @param FixedTransactionRequest $request
	 * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
	 */
	public function update(FixedTransaction $fixed_transaction, FixedTransactionRequest $request)
	{
		$updated = $fixed_transaction->update($request->all());

		if ($updated)
		{
			session()->flash('flash_message', 'La transacción fija ha sido actualizada.');
			session()->flash('flash_action', 'success');
		}
		else
		{
			session()->flash('flash_message', 'Hubo un error actualizando la transacción fija');
			session()->flash('flash_action', 'danger');
		}

		return redirect()->route('fixed-transactions.index');
	}

	/**
	 * Inactivates a fixed transaction
	 *
	 * @param FixedTransaction $fixed_transaction
	 * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
	 * @throws \Exception
	 */
	public function softDelete(FixedTransaction $fixed_transaction)
	{
		$deactivated = $fixed_transaction->delete();

		if ($deactivated)
		{
			session()->flash('flash_message', 'La transacción fija ha sido desactivada.');
			session()->flash('flash_action', 'success');
		}
		else
		{
			session()->flash('flash_message', 'Hubo un error desactivando la transacción fija');
			session()->flash('flash_action', 'danger');
		}

		return redirect()->route('fixed-transactions.index');
	}

	/**
	 * Deletes a category
	 *
	 * @param FixedTransaction $fixed_transaction
	 * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
	 */
	public function destroy(FixedTransaction $fixed_transaction)
	{
		$deleted = $fixed_transaction->forceDelete();

		if ($deleted)
		{
			session()->flash('flash_message', 'La transacción fija ha sido borrada.');
			session()->flash('flash_action', 'success');
		}
		else
		{
			session()->flash('flash_message', 'Hubo un error borrando la transacción fija');
			session()->flash('flash_action', 'danger');
		}

		return redirect()->route('fixed-transactions.index');
	}

	/**
	 * Get a fixed transaction by title. JSON for jQuery auto completion
	 *
	 * @param Request $request
	 * @return array
     */
	public function getFixedTransactionsByTitle(Request $request)
	{
		$title = $request->input('term');

		return FixedTransaction::getFixedTransactionsByTitle($title);
	}

	/**
	 * converts the fixed transactions into transactions each month
	 *
	 * @param $month
	 * @return bool
	 */
	public function generateMonthlyFixedTransactions(Request $request)
	{
		$month = $request->input('month');

		$ok = FixedTransaction::generateMonthlyFixedTransactions($month);

		if ($ok)
		{
			session()->flash('flash_message', 'Las transacción fijas se sincronizaron correctamente.');
			session()->flash('flash_action', 'success');
		}
		else
		{
			session()->flash('flash_message', 'Hubo un error sincronizando las transacción fijas');
			session()->flash('flash_action', 'danger');
		}

		return redirect()->route('fixed-transactions.index');
	}

	/**
	 * converts the fixed transactions into transactions each month, url for cron only
	 *
	 * @return bool
	 */
	public function generateMonthlyFixedTransactionsCron()
	{
		return FixedTransaction::generateMonthlyFixedTransactions();
	}
}

resources/views/fixed_transactions/_form.blade.php
<div class="form-group">

    {!! Form::label('title', 'Título:') !!}
    {!! Form::text('title', null, ['class'=>'form-control']) !!}

</div>

<div class="form-group">

    {!! Form::label('type_id', 'Tipo:') !!}
    {!! Form::select('type_id', $types, null, ['class'=>'form-control']) !!}

</div>

<div class="form-group">

    {!! Form::label('category_id', 'Categoria:') !!}
    {!! Form::select('category_id', array(0 => 'Seleccione...'), null, ['class'=>'form-control']) !!}

</div>

<div class="form-group">

    {!! Form::label('amount', 'Monto:') !!}
    <div class="input-group">
        <span class="input-group-addon">$</span>
        {!! Form::input('text','amount', null, ['class'=>'form-control']) !!}
    </div>

</div>

<div class="form-group">

    {!! Form::label('payment_day', 'Dia de pago en el mes:') !!}
    {!! Form::input('number', 'payment_day', null, ['class'=>'form-control', 'min'=>1, 'max'=>31]) !!}

</div>

<div class="form-group">

    {!! Form::submit($submitButtonText, ['class'=>'btn btn-success']) !!}

</div>

@section('javascript')
    <script>
        $( document ).ready(function() {

            var select1 = $("#type_id");

            select1.on('change', function(){

                var selectedvalue= select1.val();
                var url= "/api/categories/type/" + selectedvalue;

                $.getJSON(url, function(data){
                    var select2 = $('#category_id');
                    select2.empty();
                    select2.append($('<option></option>').html("Seleccione..."));
                    $.each(data, function(index, text) {
                        select2.append($('<option></option>').val(index).html(text));
                    });
                });
            });

            $( "#payment_day" ).datepicker();
            $( "#payment_day" ).datepicker( "option", "dateFormat", 'd' );
            $( "#payment_day" ).datepicker( 'setDate', new Date() );
            
        });
    </script>
    <script type="text/javascript" src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>   
@stop

resources/views/fixed_transactions/create.blade.php
@extends('layout')


@section('content')

	<div class="page-header">
		<h1>Crear una transacción fija</h1>
	</div>

	@include('errors._form_errors')

	<div class="well">

		{!! Form::open(['url' => 'fixed-transactions']) !!}

			@include('fixed_transactions._form', ['submitButtonText' => 'Crear'])

		{!! Form::close() !!}

	</div>

@stop

@section('javascript')
	<script>
		$('#type_id').change(function()
		{
			$.get('/api/categories/type/' + this.value, function(categories)
			{
				var $category = $('#category_id');

				$category.find('option').remove().end();

				$.each(categories, function(index, category) {
					$category.append('<option value="' + index + '">' + category + '</option>');
				});
			});
		});
	</script>
@stop

resources/views/fixed_transactions/edit.blade.php
@extends('layout')


@section('content')

    <div class="page-header">
        <h1>Editar una transacción fija</h1>
    </div>

    @include('errors._form_errors')

    <div class="well">

        {!! Form::model($fixed_transaction, ['method' => 'PATCH', 'action' => ['FixedTransactionsController@update', $fixed_transaction]]) !!}

            @include('fixed_transactions._form', ['submitButtonText' => 'Editar'])

        {!! Form::close() !!}

    </div>

@stop

resources/views/fixed_transactions/index.blade.php
@extends('layout')

@section('content')

	<div class="page-header">
		<h1>Transacciones Fijas</h1>
	</div>

	<div class="panel panel-primary">
		<!-- Default panel contents -->
		<div class="panel-heading">Acciones</div>
		<div class="panel-body">
			<a class="btn btn-success" href="{{ route('fixed-transactions.create') }}" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Crear nueva</a>
			<a class="btn btn-default" href="{{ route('fixed-transactions.indexInactive') }}"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Ver inactivas</a>
                        <a class="btn btn-default" href="{{ route('fixed-transactions.sync', ['month' => date('m')]) }}"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Sincronizar</a>
		</div>
	</div>

	@if (count($fixed_transactions))
		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
			        <tr>
			          	<th>Nombre</th>
						<th>Tipo</th>
			          	<th>Categoria</th>
						<th>Monto</th>
						<th>Dia de pago</th>
			        	<th>Acción</th>
			        </tr>
		        </thead>
		        <tbody>
				@foreach ($fixed_transactions as $fixed_transaction)

					<tr>
						<td>{{ $fixed_transaction->title }}</td>
						<td>{{ $fixed_transaction->getType() }}</td>
						<td>{{ $fixed_transaction->category->title }}</td>
						<td>{{ $fixed_transaction->present()->amount_formatted }}</td>
						<td>{{ $fixed_transaction->payment_day }} de cada mes</td>
						<td>
							<a alt="Editar" title="Editar" href="{{ route('fixed-transactions.edit', $fixed_transaction) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
							<a alt="Desactivar" title="Desactivar" href="{{ route('fixed-transactions.deactivate', $fixed_transaction) }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
						</td>
					</tr>

				@endforeach
				</tbody>
			</table>
		</div>
	@else
		<div class="alert alert-warning" role="alert">No hay datos</div>
	@endif

@stop

@section('footer')

@stop

resources/views/fixed_transactions/index_inactive.blade.php
@extends('layout')

@section('content')

    <div class="page-header">
        <h1>Transacciones Fijas inactivas</h1>
    </div>

    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">Acciones</div>
        <div class="panel-body">
            <a class="btn btn-default" href="{{ route('fixed-transactions.index') }}"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Ver activas</a>
        </div>
    </div>

    @if (count($fixed_transactions))
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Tipo</th>
                    <th>Categoria</th>
                    <th>Monto</th>
                    <th>Dia de pago</th>
                    <th>Acción</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($fixed_transactions as $fixed_transaction)

                    <tr>
                        <td>{{ $fixed_transaction->title }}</td>
                        <td>{{ $fixed_transaction->getType() }}</td>
                        <td>{{ $fixed_transaction->category->title }}</td>
                        <td>{{ $fixed_transaction->present()->amount_formatted }}</td>
                        <td>{{ $fixed_transaction->payment_day }} de cada mes</td>
                        <td>
                            <a title="Activar" alt="Activar" href="{{ route('fixed-transactions.activate', $fixed_transaction) }}"><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span></a>
                            {!! Form::model($fixed_transaction, ['method' => 'DELETE', 'action' => ['FixedTransactionsController@destroy', $fixed_transaction], 'id' => 'delete' . $fixed_transaction->id, 'class' => 'delete']) !!}
                                <a href="javascript:;" onclick="document.getElementById('delete{{ $fixed_transaction->id }}').submit();" title="Borrar permanentemente"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                            {!! Form::close() !!}
                        </td>
                    </tr>

                @endforeach
                </tbody>
            </table>
        </div>
    @else
        <div class="alert alert-warning" role="alert">No hay datos</div>
    @endif

@stop

@section('footer')

@stop

resources/views/fixed_transactions/show.blade.php
@extends('layout')

@section('content')

	<h1>Gasto Fijo #{{ $fixed_expense->id }}</h1>

	<p>Categoria: {{ $fixed_expense->category->title }}</p>
	<p>Nombre: {{ $fixed_expense->title }}</p>
	<p>Monto aproximado a pagar: {{ $fixed_expense->amount }}</p>
	<p>Dia Límite de Pago: {{ $fixed_expense->day }}</p>

@stop

@section('footer')

@stop